---
title: "MTH361: Probability and Statistics in the Health Sciences"
author: "Midterm Review"
date: "October 22, 2024"
output: 
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r echo=FALSE, message=FALSE, warning = FALSE}
library(tidyverse)
library(knitr)

hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = xfun::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

```

## Announcements

- Homework 5 due tonight at 11:59 pm!
  - I will post the answer key tomorrow
- Midterm Exam: Thursday October 24


---
## Extra Credit: Cheat Sheet

Take a piece of paper and try to make a cheat sheet for all the materials we have covered so far this semester, you need to include:

- Main topics for each week
- Important formulas we have covered

Completion of this Extra Credit assignment will result in up to 2 pts extra credit points to your midterm

Your cheat-sheet is due at the beginning of class Thursday October 24.

- Hand it to me


---
## Lab 5/6 Comments

Conclusions consist of three parts:
+ Compare p-value to $\alpha$
+ Using that, decide to Reject or Fail to Reject
+ We *(do/do not)* have evidence ...
  
Always write conclusion in terms of alternative hypothesis:
+ Answers research question
+ Just because we don't have evidence for the alternative, doesn't mean we now have evidence the null is true.
  - We are doing our calculations assuming the null is true
  - Could just have an unlucky sample
  
Make sure to include context of problem when writing hypothesis and conclusions

---
## Exam Structure

- Problem-Based - using data (~85%)
  + Short answer
  + Similar to questions on homeworks/labs
- Conceptual questions (~15%)
  + True/False, Short answer
- Please bring a calculator or let me know ASAP if you need to borrow one
- Formula Sheet provided

---
## Office Hours

I will have office hours:
- Today: 3:30-5 (Usual)
- Wednesday 3:30-5 (Additional)

TA Office Hours:
 
- Wednesday 1:50-3:30 (HLSB 518)



